apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    component: postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: sample
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-claim
      volumes:
        - name: postgres-claim
          persistentVolumeClaim:
            claimName: postgres-claim