apiVersion: v1
kind: Service
metadata:
  name: minio-cli-service
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30901 # make console available via NodePort