apiVersion: v1
kind: Service
metadata:
  name: erigon-service
spec:
  type: NodePort
  selector:
    app: erigon
  ports:
    - protocol: TCP
      port: 30303
      targetPort: 30303
      nodePort: 30303
    - protocol: UDP
      port: 30303
      targetPort: 30303
      nodePort: 30303
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30909