apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api
spec:
  hosts:
  - "*"
  gateways:
  - api-gateway
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: database-service.default.svc.cluster.local
        port:
          number: 5432
