apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: identity
spec:
  hosts:
  - "*"
  gateways:
  - http-gateway
  http:
  - name: User Management
    match:
    - uri:
        regex: \/user\/view\/.*
    rewrite:
      uri: /user-ui/index.html
    route:
    - destination:
        port:
          number: 9000
        host: minio-service.default.svc.cluster.local
  - name: User Management Routing
    match:
    - uri:
        prefix: /user
    rewrite:
      uri: /user-ui
    route:
    - destination:
        port:
          number: 9000
        host: minio-service.default.svc.cluster.local
  - name: Login provider
    match:
    - uri:
        prefix: /authn/
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 3000
        host: oidc-login.default.svc.cluster.local
    corsPolicy: &apiCorsPolicy
      allowOrigins:
      - regex: 'https://*'
      - regex: 'http://*'
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      allowCredentials: false
      allowHeaders:
      - DNT
  - name: OIDC provider
    match:
    - uri:
        prefix: /oidc/
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 4444
        host: oidc-login.default.svc.cluster.local
    corsPolicy: *apiCorsPolicy
  - name: Front End Resources
    match:
    - uri:
        regex: \/login\/view\/.*
    rewrite:
      uri: /identity-ui/index.html
    route:
    - destination:
        port:
          number: 9000
        host: minio-service.default.svc.cluster.local
  - name: Front End Routing
    match:
    - uri:
        prefix: /login
    rewrite:
      uri: /identity-ui
    route:
    - destination:
        port:
          number: 9000
        host: minio-service.default.svc.cluster.local