apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oidc
  template:
    metadata:
      labels:
        app: oidc
    spec:
      containers:
        - image: localhost:32000/oidc:latest
          imagePullPolicy: Always
          name: oidc