apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-postgres
  labels:
    app: oidc-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oidc-postgres
    spec:
      containers:
        - name: postgresql
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: sample
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-volume
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: oidc-postgres-claim