name: Deploy Minio
on: workflow_dispatch
  workflow_dispatch:
    inputs:
      bucketName:
        type: string
        default: myminio/static
        required: true
      accessKeyId:
        type: string
        default: CHANGE_ME
        required: true
      secretAccessKey:
        type: string
        default: CHANGE_ME
        required: true
jobs:
  deploy-minio:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set minio http://localhost:9001 $ACCESS_KEY_ID $SECRET_ACCESS_KEY
          ./mc mb $BUCKET_NAME
          ./mc policy wnload $BUCKET_NAME
          echo "<HTML><B>Hello World!</B></HTML>" > index.html
          ./mc cp index.html myminio/static/
        env:
          - BUCKET_NAME: ${{ github.event.inputs.bucketName }}
          - ACCESS_KEY_ID: ${{ github.event.inputs.accessKeyId }}
          - SECRET_ACCESS_KEY: ${{ github.event.inputs.secretAccessKey }}