name: Create Web Bucket
on:
  workflow_dispatch:
    inputs:
      bucketName:
        type: string
        default: static
        required: true
      accessKeyId:
        type: string
        default: CHANGE_ME
        required: true
      secretAccessKey:
        type: string
        default: CHANGE_ME
        required: true
jobs:
  create-web-bucket:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd /home/actions-runner
          ./mc alias set minio http://minio-cli-service.default.svc.cluster.local:9000 $ACCESS_KEY_ID $SECRET_ACCESS_KEY
          ./mc mb minio/$BUCKET_NAME
          ./mc policy set download minio/$BUCKET_NAME
          echo '<HTML><B>Hello World!</B></HTML>' > index.html
          ./mc cp index.html minio/$BUCKET_NAME
        env:
          BUCKET_NAME: ${{ github.event.inputs.bucketName }}
          ACCESS_KEY_ID: ${{ github.event.inputs.accessKeyId }}
          SECRET_ACCESS_KEY: ${{ github.event.inputs.secretAccessKey }}