name: Install Istio
on:
  workflow_dispatch:
    inputs:
      istioVersion:
        type: environment
        istioVersion: 1.13.2
        required: false
jobs:
  deploy-istio:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=$ISTIO_VERSION TARGET_ARCH=x86_64 sh -
          istioctl install --set profile=minimal -y
          kubectl label namespace default istio-injection=enabled
        env:
          ISTIO_VERSION: ${{ github.event.inputs.istioVersion }}