name: Install Istio
on:
  workflow_dispatch:
    inputs:
      istioVersion:
        type: string
        default: 1.13.2
        required: true
jobs:
  deploy-istio:
    runs-on: 179e2ccbaf53
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=$ISTIO_VERSION TARGET_ARCH=x86_64 sh -
          istioctl install --set profile=minimal -y
          export PATH="$PATH:/actions-runner/_work/stacker/stacker/istio-$ISTIO_VERSION/bin"
          kubectl label namespace default istio-injection=enabled
        env:
          ISTIO_VERSION: ${{ github.event.inputs.istioVersion }}