name: Inject Istio Namespace
on:
  workflow_dispatch:
    inputs:
      namespace:
        type: string
        default: default
        required: true
      istioVersion:
        type: string
        default: 1.13.2
        required: true
jobs:
  inject-istio-namespace:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=$ISTIO_VERSION TARGET_ARCH=x86_64 sh -
          export PATH="$PATH:/actions-runner/_work/stacker/stacker/istio-$ISTIO_VERSION/bin"
          kubectl label namespace $NAMESPACE istio-injection=enabled
        env:
          ISTIO_VERSION: ${{ github.event.inputs.istioVersion }}
          NAMESPACE: ${{ github.event.inputs.namespace }}

