name: Sample Service Deploy
on:
  workflow_dispatch:
    inputs:
      namespace:
        type: string
        default: default
jobs:
  build-service:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cluster/service
          docker build . -t localhost:32000/sample:latest
          docker push localhost:32000/sample:latest
          kubectl apply -k ./kustomize

